from django.contrib import admin as a
from .models import *

a.site.register(Batch)
a.site.register(SlpAdmin)
a.site.register(Category)
a.site.register(Video)
a.site.register(Quiz)
a.site.register(Reward)
a.site.register(Job)
a.site.register(Task)
a.site.register(Product)
a.site.register(Merchant)
a.site.register(Dispute)
a.site.register(Banner)
a.site.register(SlpUser)
a.site.register(Question)
a.site.register(ScannedQRCode)
a.site.register(Contractor)
a.site.register(Contest)
a.site.register(TechnicalFiles)
a.site.register(AppilicationGuideLineFiles)
a.site.register(VideoFiles)
a.site.register(SafetyFiles)
a.site.register(Certificate)
a.site.register(PointsTransaction)
a.site.register(QRCode)
a.site.register(UserToken)

